spring:
  h2:
    console:
      enabled: true # ??? DB? ? ? ?? ?
      path: /h2-console # ?? ?? (???)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # ? ?? ? ???? ???? ?? (???)
    show-sql: true     # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL? ??? ??